name: Sync articles to production server

on: [push, pull_request]

jobs:
  sync_articles:
    name: Sync articles to production server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - run: curl https://php.baraja.cz/sync-all
